import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { form, FormField, required, submit } from '@angular/forms/signals';

import { MailserverService } from '../../../core/mailserver.service';
import { DkimKey } from '../../../core/mailserver.models';
import { copyText, mailserverErrorMessage } from '../mailserver.utils';

/** DKIM public records generated by the mailserver, and key generation. */
@Component({
  selector: 'app-mailserver-dkim',
  imports: [FormField],
  templateUrl: './dkim.html',
  styleUrl: './dkim.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Dkim {
  private readonly mailserver = inject(MailserverService);

  protected readonly keys = signal<DkimKey[]>([]);
  protected readonly loading = signal(false);
  protected readonly error = signal<string | null>(null);
  protected readonly success = signal<string | null>(null);
  protected readonly generating = signal(false);

  protected readonly dkimModel = signal({ domain: '', selector: 'mail', keySize: '2048' });
  protected readonly dkimForm = form(this.dkimModel, (path) => {
    required(path.selector, { message: 'A selector is required' });
  });

  constructor() {
    void this.load();
  }

  private async load(): Promise<void> {
    this.loading.set(true);
    this.error.set(null);
    try {
      this.keys.set(await this.mailserver.listDkimKeys());
    } catch {
      this.error.set('Unable to load the DKIM records.');
    } finally {
      this.loading.set(false);
    }
  }

  protected onGenerate(): void {
    this.error.set(null);
    this.success.set(null);
    submit(this.dkimForm, async () => {
      const value = this.dkimModel();
      this.generating.set(true);
      try {
        this.keys.set(
          await this.mailserver.generateDkim({
            domain: value.domain.trim().toLowerCase() || null,
            selector: value.selector.trim() || 'mail',
            key_size: parseInt(value.keySize) as 1024 | 2048 | 4096,
          }),
        );
        this.success.set('DKIM keys generated.');
      } catch (err) {
        this.error.set(mailserverErrorMessage(err));
      } finally {
        this.generating.set(false);
      }
    });
  }

  protected copy(text: string): void {
    void copyText(text);
  }
}
